//mainInfoAction
export const GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST' = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILED: 'GET_ITEMS_FAILED' = 'GET_ITEMS_FAILED'


export const ADD_ITEMS_OTHER_COUNT: 'ADD_ITEMS_OTHER_COUNT' = 'ADD_ITEMS_OTHER_COUNT'
export const ADD_ITEMS_BUN_COUNT: 'ADD_ITEMS_BUN_COUNT' = 'ADD_ITEMS_BUN_COUNT'
export const REMOVE_ITEMS_COUNT: 'REMOVE_ITEMS_COUNT' = 'REMOVE_ITEMS_COUNT'
export const REFRESH_ITEMS_COUNT: 'REFRESH_ITEMS_COUNT' = 'REFRESH_ITEMS_COUNT'
//authAction
export const POST_USER_REQUEST: 'POST_USER_REQUEST' = 'POST_USER_REQUEST'
export const POST_USER_SUCCESS: 'POST_USER_SUCCESS' = 'POST_USER_SUCCESS'
export const POST_USER_ERROR: 'POST_USER_ERROR' = 'POST_USER_ERROR'

export const SIGN_USER_REQUEST: 'AUTH_USER_REQUEST' = 'AUTH_USER_REQUEST'
export const SIGN_USER_SUCCESS: 'AUTH_USER_SUCCESS' = 'AUTH_USER_SUCCESS'
export const SIGN_USER_ERROR: 'AUTH_USER_ERROR' = 'AUTH_USER_ERROR'

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR'

export const REFRESH_USER_REQUEST: 'REFRESH_USER_REQUEST' = 'REFRESH_USER_REQUEST'
export const REFRESH_USER_SUCCESS: 'REFRESH_USER_SUCCESS' = 'REFRESH_USER_SUCCESS'
export const REFRESH_USER_ERROR: 'REFRESH_USER_ERROR' = 'REFRESH_USER_ERROR'

export const REFRESH_COOKIES_REQUEST: 'REFRESH_COOKIES_REQUEST' = 'REFRESH_COOKIES_REQUEST'
export const REFRESH_COOKIES_SUCCESS: 'REFRESH_COOKIES_SUCCESS' = 'REFRESH_COOKIES_SUCCESS'
export const REFRESH_COOKIES_ERROR: 'REFRESH_COOKIES_ERROR' = 'REFRESH_COOKIES_ERROR'

export const LOGOUT__USER_REQUEST: 'SIGN_OUT__USER_REQUEST' = 'SIGN_OUT__USER_REQUEST'
export const LOGOUT__USER_SUCCESS: 'SIGN_OUT__USER_SUCCESS' = 'SIGN_OUT__USER_SUCCESS'
export const LOGOUT__USER_ERROR: 'SIGN_OUT__USER_ERROR' = 'SIGN_OUT__USER_ERROR'

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR' = 'FORGOT_PASSWORD_ERROR'

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR' = 'RESET_PASSWORD_ERROR'

export const ADD_ITEM_BUN: 'ADD_ITEM_BUN' = 'ADD_ITEM_BUN'
export const ADD_ITEM_OTHER: 'ADD_ITEM_OTHER' = 'ADD_ITEM_OTHER'
export const REMOVE_ITEM: 'REMOVE_ITEM' = 'REMOVE_ITEM'
export const MOVE_ITEM: 'MOVE_ITEM' = 'MOVE_ITEM'
export const REFRESH_ITEMS: 'REFRESH_ITEMS' = 'REFRESH_ITEMS'

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED'

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
